pipeline {
    agent any

    stages {
        stage('Checkout Code From Git') {
            steps {
                    git url: 'https://github.com/BankThanomsup/Automated_Test_Thitikorn.git', branch: 'main', credentialsId: 'github-test-token'
            }
        }

        stage('Install Robot Framework') {
            steps {
                bat '''
                pip install robotframework
                pip install --quiet robotframework robotframework-seleniumlibrary
                '''
            }
        }

        stage('Run login_test.robot') {
            steps {
                    bat '''
                    cd Tests\\assignment2
                    robot login_test.robot
                    '''
            }
        }

        stage('Publish Results') {
            steps {
                robot outputDirectory: '.' 
            }
        }
    }
}
