pipeline {
    agent any

    stages {
        stage('Checkout Code From Git') {
            steps {
                git url: 'https://github.com/BankThanomsup/Automated_Test_Thitikorn', branch: 'main'
            }
        }

        stage('Run Test Automate') {
            steps {
                sh 'npm install'      
                sh 'npx playwright test'  
            }
        }

        stage('Send Result To Jenkins') {
            steps {
                junit 'results/*.xml' 
            }
        }
    }
}